
const DEFAULT_FIREBASE_CONFIG={apiKey:"AIzaSyDmupiTTuxwYZPci-lFehUL1pNv9TV8CE8",authDomain:"raymond-df295.firebaseapp.com",projectId:"raymond-df295",storageBucket:"raymond-df295.firebasestorage.app",messagingSenderId:"36554452985",appId:"1:36554452985:web:51546aaf1ba16d536d5728"};
const DEFAULT_ADMIN_CODE="Raymond0@.";
function getAdminCode(){return localStorage.getItem('admin_code')||DEFAULT_ADMIN_CODE}
function checkAdminCode(){let i=document.getElementById('adminCodeInput'),e=document.getElementById('loginError'),o=document.getElementById('loginOverlay');if(i.value===getAdminCode()){localStorage.setItem('raymond_auth','true');o.style.display='none';o.classList.remove('show');document.body.classList.remove('locked');}else{e.innerText='Wrong code! Enter correct code.';e.classList.add('show');}}
function changeAdminCode(){let c=document.getElementById('currentAdminCode').value,n=document.getElementById('newAdminCode').value,f=document.getElementById('confirmAdminCode').value;if(c!==getAdminCode())return alert('Wrong');if(n!==f)return alert('Mismatch');localStorage.setItem('admin_code',n);alert('Changed');}
function logoutAdmin(){localStorage.removeItem('raymond_auth'); if(window.location.href.includes('/app/')){ window.location.href='../index.html'; return; }localStorage.removeItem('raymond_auth');localStorage.removeItem('raymond_auth');window.location.href='../index.html';}
const DB_KEY='raymond_v2_db',ATT_KEY='raymond_attendance_v2';
function loadDB(){let d=localStorage.getItem(DB_KEY);if(!d)return{orders:[],customers:[],staff:[],products:[],tailoredProducts:[],sizeSegments:{},nextSlip:1,lastSync:0};try{let p=JSON.parse(d);if(!p.tailoredProducts)p.tailoredProducts=[];if(!p.sizeSegments)p.sizeSegments={};return p}catch{return{orders:[],customers:[],staff:[],products:[],tailoredProducts:[],sizeSegments:{},nextSlip:1,lastSync:0}}}
function saveDB(db){db.lastSync=Date.now();localStorage.setItem(DB_KEY,JSON.stringify(db));if(window.firebaseReady)syncToFirebase(db);updateDash();}
let db=loadDB();let firebaseReady=false,fb_db=null;
function getFirebaseConfig(){try{return JSON.parse(localStorage.getItem('firebase_config'))||DEFAULT_FIREBASE_CONFIG}catch{return DEFAULT_FIREBASE_CONFIG}}
function initFirebase(){try{let cfg=getFirebaseConfig();if(!firebase.apps.length)firebase.initializeApp(cfg);fb_db=firebase.firestore();firebaseReady=true;window.firebaseReady=true;fb_db.collection('meta').doc('raymond').onSnapshot(d=>{if(d.exists){let data=d.data();if(data.updatedAt>(db.lastSync||0)+1000){db=data.payload;if(!db.tailoredProducts)db.tailoredProducts=[];if(!db.sizeSegments)db.sizeSegments={};localStorage.setItem(DB_KEY,JSON.stringify(db));renderAll();}}});document.getElementById('fbStatus').innerText='Connected';}catch(e){}}
function syncToFirebase(p){if(!fb_db)return;fb_db.collection('meta').doc('raymond').set({payload:p,updatedAt:Date.now()});}
function parseBulkConfig(){let b=document.getElementById('bulkFirebasePaste').value;let ex=k=>{let m=b.match(new RegExp(k+'\\s*:\\s*["\']([^"\']+)["\']','i'));return m?m[1]:''};let cfg={apiKey:ex('apiKey'),authDomain:ex('authDomain'),projectId:ex('projectId'),storageBucket:ex('storageBucket'),messagingSenderId:ex('messagingSenderId'),appId:ex('appId')};localStorage.setItem('firebase_config',JSON.stringify(cfg));location.reload();}
let currentPortalSub='readymade',currentSettingsSub='shopinfo';
function switchTab(tab){document.querySelectorAll('.nav-item').forEach(n=>n.classList.remove('active'));let nav=document.getElementById('nav-'+tab);if(nav)nav.classList.add('active');document.querySelectorAll('.tab-content').forEach(t=>t.style.display='none');document.getElementById('tab-'+tab).style.display='block';document.getElementById('topTitle').innerText=tab;let ps=document.getElementById('portalSubSidebar'),ss=document.getElementById('settingsSubSidebar');if(ps)ps.classList.remove('show');if(ss)ss.classList.remove('show');if(tab==='portal'){ps.classList.add('show');switchPortalSub(currentPortalSub);}else if(tab==='settings'){ss.classList.add('show');switchSettingsSub(currentSettingsSub);}if(tab==='order-slip')renderOrderSlip();if(tab==='customers')renderCustomers();if(tab==='daily-presents')renderAttendance();}
function switchPortalSub(sub){currentPortalSub=sub;document.querySelectorAll('#portalSubSidebar .sub-nav-item').forEach(n=>n.classList.remove('active'));document.getElementById('sub-'+sub).classList.add('active');document.querySelectorAll('.portal-sub-content').forEach(c=>c.style.display='none');document.getElementById('portal-'+sub).style.display='block';if(sub==='readymade')renderPortalProducts();if(sub==='tailored')renderTailoredProducts();if(sub==='size')renderSizeSegments();if(sub==='staff')renderStaff();}
function switchSettingsSub(sub){currentSettingsSub=sub;document.querySelectorAll('#settingsSubSidebar .sub-nav-item').forEach(n=>n.classList.remove('active'));document.getElementById('sub-'+sub).classList.add('active');document.querySelectorAll('.settings-sub-content').forEach(c=>c.style.display='none');document.getElementById('settings-'+sub).style.display='block';}
function toggleMobileMenu(){let sb=document.querySelector('.sidebar');sb.classList.toggle('mobile-open');}
function toggleDropdown(){document.getElementById('plusDropdown').classList.toggle('show');}
function openNewOrder(){document.getElementById('plusDropdown').classList.remove('show');if(db.tailoredProducts.length===0&&!confirm('No Tailored Products! Add first?'))return;populateProductDropdown();document.getElementById('orderSlipPreview').innerText=' - Slip #'+db.nextSlip;document.getElementById('orderModal').classList.add('show');}
function closeOrderModal(){document.getElementById('orderModal').classList.remove('show');}
function populateProductDropdown(){let sel=document.getElementById('f_type');sel.innerHTML='';if(db.tailoredProducts.length===0){sel.innerHTML='<option>No products</option>';document.getElementById('noProductMsg').style.display='block';}else{document.getElementById('noProductMsg').style.display='none';db.tailoredProducts.forEach(p=>{let o=document.createElement('option');o.value=p.name;o.innerText=p.name;sel.appendChild(o);});}renderDynamicSizes();}
function renderDynamicSizes(){let prod=document.getElementById('f_type').value,cont=document.getElementById('dynamicSizeFields');cont.innerHTML='';let segs=db.sizeSegments[prod]||[];if(segs.length===0){cont.innerHTML='<div class="form-group full" style="padding:12px;background:#fff3cd;border-radius:4px;font-size:12px">No size segments for '+prod+'. Add in Portal > Size Segments</div>';return;}segs.forEach(s=>{let d=document.createElement('div');d.className='form-group';d.innerHTML='<label>'+s+'</label><input data-size="'+s+'" placeholder="'+s+'">';cont.appendChild(d);});}
document.getElementById('orderForm').addEventListener('submit',function(e){e.preventDefault();let name=document.getElementById('f_name').value,mobile=document.getElementById('f_mobile').value,type=document.getElementById('f_type').value;if(!type||type.includes('No products'))return alert('Select product');let sizes={};document.querySelectorAll('#dynamicSizeFields input[data-size]').forEach(inp=>{sizes[inp.dataset.size]=inp.value;});let order={id:Date.now(),slipNo:db.nextSlip,name,mobile,type,fabric:document.getElementById('f_fabric').value,qty:parseInt(document.getElementById('f_qty').value)||1,delivery:document.getElementById('f_delivery').value,total:parseFloat(document.getElementById('f_total').value)||0,advance:parseFloat(document.getElementById('f_advance').value)||0,notes:document.getElementById('f_notes').value,sizes,status:'Pending',createdAt:new Date().toISOString()};order.due=order.total-order.advance;db.orders.push(order);db.nextSlip++;if(!db.customers.find(c=>c.mobile===mobile))db.customers.push({id:Date.now(),name,mobile});saveDB(db);closeOrderModal();this.reset();alert('Saved #'+order.slipNo);renderAll();});
function renderOrderSlip(){let el=document.getElementById('orderSlipList');if(!db.orders.length){el.innerHTML='<div class="empty">No orders</div>';return;}let h='<table class="table"><tr><th>Slip</th><th>Customer</th><th>Product</th><th>Total</th></tr>';db.orders.slice().reverse().forEach(o=>{h+='<tr onclick="viewSlip('+o.id+')"><td>#'+o.slipNo+'</td><td>'+o.name+'</td><td>'+o.type+'</td><td>৳'+o.total+'</td></tr>';});el.innerHTML=h+'</table>';}
function viewSlip(id){let o=db.orders.find(o=>o.id===id);if(!o)return;let s='';if(o.sizes){s='<br>Measurements: ';for(let k in o.sizes){s+=k+':'+o.sizes[k]+' | ';}}document.getElementById('slipDetail').innerHTML='<div style="padding:20px">Slip #'+o.slipNo+'<br>'+o.name+'<br>'+o.type+s+'<br>Total ৳'+o.total+'<br><button class="btn btn-gray" onclick="deleteOrder('+o.id+')">Delete</button></div>';document.getElementById('slipModal').classList.add('show');}
function deleteOrder(id){if(confirm('Delete?')){db.orders=db.orders.filter(o=>o.id!==id);saveDB(db);document.getElementById('slipModal').classList.remove('show');renderOrderSlip();}}
function renderCustomers(){let el=document.getElementById('customerList');if(!db.customers.length){el.innerHTML='<div class="empty">No customers</div>';return;}let h='<table class="table"><tr><th>Name</th><th>Mobile</th></tr>';db.customers.forEach(c=>{h+='<tr><td>'+c.name+'</td><td>'+c.mobile+'</td></tr>';});el.innerHTML=h+'</table>';}
function getTodayStr(){return new Date().toISOString().split('T')[0];}
function loadAttendance(){let d=localStorage.getItem(ATT_KEY);return d?JSON.parse(d):{};}
function saveAttendance(a){localStorage.setItem(ATT_KEY,JSON.stringify(a));}
function renderAttendance(){let el=document.getElementById('attendanceList');if(!db.staff.length){el.innerHTML='<div class="empty">No staff</div>';return;}let att=loadAttendance(),today=getTodayStr(),todayAtt=att[today]||{};let h='';db.staff.forEach(s=>{let p=!!todayAtt[s.id];h+='<div class="attendance-row"><div><b>'+s.name+'</b></div><button class="btn '+(p?'btn-red':'btn-gray')+'" onclick="toggleAttendance('+s.id+')">'+(p?'Present':'Mark')+'</button></div>';});el.innerHTML=h;}
function toggleAttendance(id){let att=loadAttendance(),today=getTodayStr();if(!att[today])att[today]={};if(att[today][id])delete att[today][id];else att[today][id]={time:new Date().toLocaleString()};saveAttendance(att);renderAttendance();updateDash();}
function renderPortalProducts(){let el=document.getElementById('portalProductList');if(!el)return;el.innerHTML=db.products.length?db.products.map(p=>'<div class="attendance-row"><div><b>'+p.name+'</b> ৳'+p.price+'</div><button class="btn btn-gray" onclick="deleteProduct('+p.id+')">Del</button></div>').join(''):'<div class="empty">No products</div>';}
function addProduct(){let n=document.getElementById('prodName').value;if(!n)return alert('Name');db.products.push({id:Date.now(),name:n,price:parseFloat(document.getElementById('prodPrice').value)||0,stock:parseInt(document.getElementById('prodStock').value)||0});saveDB(db);renderPortalProducts();}
function deleteProduct(id){db.products=db.products.filter(p=>p.id!==id);saveDB(db);renderPortalProducts();}
function renderTailoredProducts(){let el=document.getElementById('tailoredProductList'),sel=document.getElementById('sizeProductSelect');if(el)el.innerHTML=db.tailoredProducts.length?db.tailoredProducts.map(p=>'<div class="attendance-row"><div><b>'+p.name+'</b></div><button class="btn btn-gray" onclick="deleteTailoredProduct('+p.id+')">Del</button></div>').join(''):'<div class="empty">Add Shirt, Pant etc</div>';if(sel){let cur=sel.value;sel.innerHTML='<option value="">Select</option>';db.tailoredProducts.forEach(p=>{let o=document.createElement('option');o.value=p.name;o.innerText=p.name;sel.appendChild(o);});if(cur)sel.value=cur;}}
function addTailoredProduct(){let n=document.getElementById('tailoredName').value.trim();if(!n)return alert('Name');if(db.tailoredProducts.find(p=>p.name===n))return alert('Exists');db.tailoredProducts.push({id:Date.now(),name:n});if(!db.sizeSegments[n])db.sizeSegments[n]=[];saveDB(db);document.getElementById('tailoredName').value='';renderTailoredProducts();}
function deleteTailoredProduct(id){let p=db.tailoredProducts.find(x=>x.id===id);if(!confirm('Delete '+p.name+'?'))return;db.tailoredProducts=db.tailoredProducts.filter(x=>x.id!==id);delete db.sizeSegments[p.name];saveDB(db);renderTailoredProducts();renderSizeSegments();}
function renderSizeSegments(){let prod=document.getElementById('sizeProductSelect').value,list=document.getElementById('sizeSegmentsList');if(!prod){list.innerHTML='Select product';return;}let segs=db.sizeSegments[prod]||[];list.innerHTML=segs.length?segs.map((s,i)=>'<div class="attendance-row"><div>'+s+'</div><button class="btn btn-gray" onclick="deleteSizeSegment(\''+prod+'\','+i+')">Del</button></div>').join(''):'No segments - Add Height, Chest etc';}
function addSizeSegment(){let prod=document.getElementById('sizeProductSelect').value;if(!prod)return alert('Select product');let n=document.getElementById('newSizeName').value.trim();if(!n)return alert('Name');if(!db.sizeSegments[prod])db.sizeSegments[prod]=[];db.sizeSegments[prod].push(n);saveDB(db);document.getElementById('newSizeName').value='';renderSizeSegments();}
function deleteSizeSegment(prod,idx){db.sizeSegments[prod].splice(idx,1);saveDB(db);renderSizeSegments();}
function renderStaff(){let el=document.getElementById('portalStaffList');if(!el)return;el.innerHTML=db.staff.length?db.staff.map(s=>'<div class="attendance-row"><div>'+s.name+' - '+s.role+'</div><button class="btn btn-gray" onclick="deleteStaff('+s.id+')">Del</button></div>').join(''):'No staff';}
function addStaff(){let n=document.getElementById('staffName').value;if(!n)return alert('Name');db.staff.push({id:Date.now(),name:n,role:document.getElementById('staffRole').value,phone:document.getElementById('staffPhone').value,salary:document.getElementById('staffSalary').value});saveDB(db);renderStaff();}
function deleteStaff(id){db.staff=db.staff.filter(s=>s.id!==id);saveDB(db);renderStaff();}
function openSale(){document.getElementById('plusDropdown').classList.remove('show');document.getElementById('saleModal').classList.add('show');}
function saveShopInfo(){localStorage.setItem('shop_info',JSON.stringify({name:document.getElementById('shopName').value,address:document.getElementById('shopAddress').value,phone:document.getElementById('shopPhone').value}));alert('Saved');}
function saveFirebaseConfig(){let cfg={apiKey:document.getElementById('fb_apiKey').value,authDomain:document.getElementById('fb_authDomain').value,projectId:document.getElementById('fb_projectId').value,storageBucket:document.getElementById('fb_storageBucket').value,messagingSenderId:document.getElementById('fb_messagingSenderId').value,appId:document.getElementById('fb_appId').value};localStorage.setItem('firebase_config',JSON.stringify(cfg));location.reload();}
function testFirebase(){alert('Connected');}
function clearAllData(){if(confirm('Clear?')){localStorage.clear();location.reload();}}
function renderAll(){renderOrderSlip();renderCustomers();renderPortalProducts();renderTailoredProducts();renderSizeSegments();renderStaff();updateDash();}
function updateDash(){let dc=document.getElementById('dashOrderCount');if(dc)dc.innerText=db.orders.length;let cc=document.getElementById('dashCustomerCount');if(cc)cc.innerText=db.customers.length;let st=document.getElementById('dashSaleTotal');if(st)st.innerText='৳ '+db.orders.reduce((s,o)=>s+o.total,0);}
window.onload=function(){let o=document.getElementById('loginOverlay'),logged=localStorage.getItem('raymond_auth')==='true';if(logged){o.style.display='none';document.body.classList.remove('locked');}else{o.classList.add('show');o.style.display='flex';}initFirebase();let eff=getFirebaseConfig();['fb_apiKey','fb_authDomain','fb_projectId','fb_storageBucket','fb_messagingSenderId','fb_appId'].forEach((id,i)=>{let k=['apiKey','authDomain','projectId','storageBucket','messagingSenderId','appId'][i];let el=document.getElementById(id);if(el)el.value=eff[k]||'';});renderAll();updateDash();document.getElementById('todayDate').innerText=new Date().toLocaleDateString();};
